title: blogs.or.id
default_lang: en
author:
  name: adijaya
  email: adijaya@gmail.com
taxonomies:
  - tag
metadata:
  description: 'blogs.or.id adalah kumpulan para content creator demi kemajuan bangsa '
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
description: 'Media Konten Sehat'
owner:
  name: 'adijaya'
  email: adijaya@gmail.com
  description: 'Awesome Dude, Awesome Life'
  twitter: blogsorid
  facebook: blogsorid
  github: blogsorid
  instagram: blogsorid
  google_plus: 'https://plus.google.com/+blogsorid'
logo: /user/themes/notepad/images/logo.png
links:
  -
    title: 'Featured Posts'
    url: /featured
  -
    title: Categories
    url: /categories
  -
    title: About
    url: /about
include:
  - .htaccess
exclude:
  - lib
  - config.rb
  - Gemfile
  - Capfile
  - Gemfile.lock
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - less
  - '*.sublime-project'
  - '*.sublime-workspace'
  - test
  - spec
  - Gruntfile.js
  - package.json
  - node_modules
