baseURL = 'https://blogs.or.id/'
languageCode = 'en-us'
title = 'blogs Or ID '
theme = "accessible-minimalism"
ignoreErrors = ["error-missing-instagram-accesstoken"]
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
