title: 'Blogs ORang InDonesia'
header_img:
    url: assets/img/home-bg.jpg
comments:
    enabled: false
    disqus_shortname: ''
social_networks:
    twitter: spress_cms
    facebook: blogsorid
    instagram: blogsorid
    github: 'https://github.com/spress/Spress'
    dribbble: null
    linkedin: null
    email: admin@blogs.or.id
forms:
    contact: { getsimpleform_api_token: null }
themes:
    name: spress-add-ons/clean-blog-theme
